# Generated by Django 5.2.1 on 2025-06-07 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "country"), name="unique_city_country"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherDay",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(db_index=True)),
                ("temperature_max", models.FloatField(null=True)),
                ("temperature_min", models.FloatField(null=True)),
                (
                    "weather_code",
                    models.IntegerField(
                        choices=[
                            (0, "Clear sky"),
                            (1, "Mainly clear"),
                            (2, "Partly cloudy"),
                            (3, "Overcast"),
                            (45, "Fog"),
                            (48, "Depositing rime fog"),
                            (51, "Light drizzle"),
                            (53, "Moderate drizzle"),
                            (55, "Dense drizzle"),
                            (56, "Light freezing drizzle"),
                            (57, "Dense freezing drizzle"),
                            (61, "Slight rain"),
                            (63, "Moderate rain"),
                            (65, "Heavy rain"),
                            (66, "Light freezing rain"),
                            (67, "Heavy freezing rain"),
                            (71, "Slight snow fall"),
                            (73, "Moderate snow fall"),
                            (75, "Heavy snow fall"),
                            (77, "Snow grains"),
                            (80, "Slight rain showers"),
                            (81, "Moderate rain showers"),
                            (82, "Violent rain showers"),
                            (85, "Slight snow showers"),
                            (86, "Heavy snow showers"),
                            (95, "Thunderstorm"),
                            (96, "Thunderstorm with slight hail"),
                            (99, "Thunderstorm with heavy hail"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="weather.city"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("city", "date"), name="unique_city_date"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("temperature_max__isnull", True),
                                ("temperature_min__isnull", True),
                            ),
                            models.Q(
                                ("temperature_max__isnull", False),
                                ("temperature_min__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="min_and_max_temperature_both_null_or_filled",
                    ),
                ],
            },
        ),
    ]
